### ISSUE TITLE
[Bug] Сan't write April 1st from 1981 to 1984

### ISSUE THREAD

**Issue by vladseroff** [mengxiong10/vue2-datepicker#585] opened 2021-03-24 14:43 UTC
It is not possible to enter the following dates on your own:
01.04.1981;
01.04.1982;
01.04.1983;
01.04.1984.

In all cases, the previous day is set.

You can also watch it in the official demo

**Comment by alexzhivil** [comment] 2021-03-25 06:46
Same issue with 26th of March 2021 when using alongside valueType='format'

**Comment by mengxiong10** [comment] 2021-03-25 10:47
@vladseroff Did you set the corrent format.
![image](https://user-images.githubusercontent.com/14135808/112461036-80c7f480-8d9a-11eb-9d01-3fb32297974b.png)

**Comment by alexzhivil** [comment] 2021-03-25 12:43
> @vladseroff Did you set the corrent format.
> ![image](https://user-images.githubusercontent.com/14135808/112461036-80c7f480-8d9a-11eb-9d01-3fb32297974b.png)

Yes, it happens in the demo page as well.
It's related to the local timezone on the machine. I'm setting the component with an American format 'MM-DD-YYYY', but my local machine is UTC+2 Jerusalem, time. 
Once I change my local timezone to something in the US, it works fine.
The one thing that is unique to the 26th is that we are moving to Daylight Saving Time tonight.
No idea why or how it affects the datepicker, but I noticed the issue a while ago, so it's unrelated to the fact that the day is tomorrow.

![image](https://user-images.githubusercontent.com/32412580/112471198-42b7da00-8d74-11eb-8d5c-3d5a22dbb994.png)

**Comment by mengxiong10** [comment] 2021-08-09 02:53
@alexzhivil I can't reproduce this problem, but v3.9.3 maybe fix it.
If not, please visit this link(https://codesandbox.io/s/vue2-datepicker-value-type-bug-b9sih?file=/src/App.vue) and send me a screenshot

**Comment by mengxiong10** [comment] 2021-08-19 03:23
v3.9.2 fixed it

**Closed by mengxiong10** 2021-08-19 03:23 UTC
